// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, db push, studio) need DIRECT_URL (session pooler) rather
    // than DATABASE_URL (transaction pooler), which doesn't support the prepared
    // statements/advisory locks migrations rely on. The running app never loads this
    // file - PrismaService reads DATABASE_URL directly - so this only affects the CLI.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
